# Generated by Django 5.0.7 on 2024-08-07 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_automate_capteur_typedecapteur_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('relative_humidity', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('soil_temperature', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', related_query_name='utilisateur', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', related_query_name='utilisateur', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_values', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meteo_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meteodata')),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weatherdata')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellealerte', models.CharField(max_length=100)),
                ('descriptionalerte', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weather_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weatherprediction')),
            ],
        ),
    ]
