# Generated by Django 5.0.7 on 2024-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_secret',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
